courseify/courseify/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from payments.views import PaymentView,chargeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('courses.urls',namespace='courses')),
    #path('users/',include('accounts.urls',namespace='accounts')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('register/',user_views.Register,name='register'),
    path('logout/',auth_views.LogoutView.as_view(),name="logout"),
    path('profile/',user_views.ProfileView,name='profile'),
    path('payments/<int:pk>',PaymentView,name='payments'),
    path('payments/chargeView',chargeView,name='chargeView'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

courseify/courses/urls.py
#from django.contrib import admin
from django.urls import path,include
from .views import CourseListView,CourseDetailView,my_course_list_view

app_name='courses'

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',CourseListView.as_view(),name='courselist'),
    path('<int:pk>',CourseDetailView.as_view(),name='courseDetail'),
    path('my_course_list',my_course_list_view,name='purchased_course_list'),
]

courseify/courses/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Course(models.Model):
    course_name=models.CharField(max_length=20)
    description=models.CharField(max_length=50)
    price=models.IntegerField(default=0)

    def __str__(self):
        return self.course_name

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')

class CourseTransactions(models.Model):
    course_name=models.ForeignKey(Course,on_delete=models.CASCADE)
    user_name=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

class Lesson(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    lesson_name=models.CharField(max_length=20)
    position=models.IntegerField()
    video_url=models.CharField(max_length=50)
    thumbnail=models.ImageField(null=True)

    def __str__(self):
        return self.lesson_name

courseify/courses/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,View
from .models import Course,CourseTransactions

# Create your views here.

class CourseListView(ListView):
    model=Course

class CourseDetailView(View):
    def get(self,request,pk,*args,**kwargs):
        course_qs=Course.objects.filter(pk=pk)
        context={'object':course_qs[0]}
        if request.user.is_authenticated:
            ct_qs=CourseTransactions.objects.filter(course_name=course_qs[0]).filter(user_name=request.user)
            context['purchased_this']=ct_qs.exists()
        
        #print(ct_qs)
        return render(request,"courses/course_detail.html",context)

def my_course_list_view(request):
    ct_qs=CourseTransactions.objects.filter(user_name=request.user)
    return render(request,'courses/my_course_list.html',{'course_list':ct_qs})

courseify/courses/templates/courses/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

courseify/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block content %}

<h1>{{object.course_name}}</h1>
{% ifnotequal object.price 0 %}
{% if purchased_this %}
You've Already Purchased This Courses
{% else %}
<h1>{{object.price}}</h1>
<a href="{%  url 'payments' object.pk %}">Purchase</a>
{% endif %}
{% else %}
<small>Free</small>
{% endifnotequal %}
{% for l in object.lessons %}
<br>
<img src="{{l.thumbnail.url}}">

<!--This Link should be provided only if the users has purchased this course or the course is free-->

<a href="{{l.video_url}}">{{l.lesson_name}}</a>
{% endfor %}
{% endblock %}

courseify/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}

{% block content %}

{% if request.user.is_authenticated %}
Hello {{request.user}}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'courses:purchased_course_list' %}">My Course List</a>
<a href="{% url 'profile' %}">My Profile</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}
<br>
{% for c in object_list %}
<a href="{% url 'courses:courseDetail' c.pk %}">{{c.course_name}}</a>
<p>{{c.description}}</p>
<small>{{c.price}}</small>
<br>
{% endfor %}
{% endblock %}

courseify/courses/templates/courses/my_course_list.html
{% extends 'courses/base.html' %}

{% block content %}

{% for c in course_list %}
<a href="{% url 'courses:courseDetail' c.course_name.pk %}">{{c.course_name}}</a>
<p>{{c.course_name.description}}</p>
<br>
{% endfor %}

{% endblock %}

courseify/courses/templates/courses/temp_course_list.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Full Motion by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>

<head>
    <title>Full Motion</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'courses/main.css' %}" />
</head>

<body id="top">

    <!-- Banner -->
    <!--
				To use a video as your background, set data-video to the name of your video without
				its extension (eg. images/banner). Your video must be available in both .mp4 and .webm
				formats to work correctly.
			-->
    <section id="banner" data-video="images/banner">
        <div class="inner">
            <header>
                <h1>Full Motion</h1>
                <p>A responsive video gallery template with a functional lightbox<br />
                    designed by <a href="https://templated.co/">Templated</a> and released under the Creative Commons
                    License.</p>
            </header>
            <a href="#main" class="more">Learn More</a>
        </div>
    </section>

    <!-- Main -->
    <div id="main">
        <div class="inner">

            <!-- Boxes -->
            <div class="thumbnails">

                <div class="box">
                    <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="images/pic01.jpg" alt="" /></a>
                    <div class="inner">
                        <h3>Nascetur nunc varius commodo</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc
                            non. Mi accumsan.</p>
                        <a href="https://youtu.be/s6zR2T9vn2c" class="button fit"
                            data-poptrox="youtube,800x400">Watch</a>
                    </div>
                </div>

                <div class="box">
                    <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="images/pic02.jpg" alt="" /></a>
                    <div class="inner">
                        <h3>Nascetur nunc varius commodo</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc
                            non. Mi accumsan.</p>
                        <a href="https://youtu.be/s6zR2T9vn2c" class="button style2 fit"
                            data-poptrox="youtube,800x400">Watch</a>
                    </div>
                </div>

                <div class="box">
                    <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="images/pic03.jpg" alt="" /></a>
                    <div class="inner">
                        <h3>Nascetur nunc varius commodo</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc
                            non. Mi accumsan.</p>
                        <a href="https://youtu.be/s6zR2T9vn2c" class="button style3 fit"
                            data-poptrox="youtube,800x400">Watch</a>
                    </div>
                </div>

                <div class="box">
                    <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="images/pic04.jpg" alt="" /></a>
                    <div class="inner">
                        <h3>Nascetur nunc varius commodo</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc
                            non. Mi accumsan.</p>
                        <a href="https://youtu.be/s6zR2T9vn2c" class="button style2 fit"
                            data-poptrox="youtube,800x400">Watch</a>
                    </div>
                </div>

                <div class="box">
                    <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="images/pic05.jpg" alt="" /></a>
                    <div class="inner">
                        <h3>Nascetur nunc varius commodo</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc
                            non. Mi accumsan.</p>
                        <a href="https://youtu.be/s6zR2T9vn2c" class="button style3 fit"
                            data-poptrox="youtube,800x400">Watch</a>
                    </div>
                </div>

                <div class="box">
                    <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="images/pic06.jpg" alt="" /></a>
                    <div class="inner">
                        <h3>Nascetur nunc varius commodo</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc
                            non. Mi accumsan.</p>
                        <a href="https://youtu.be/s6zR2T9vn2c" class="button fit"
                            data-poptrox="youtube,800x400">Watch</a>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <h2>Etiam veroeros lorem</h2>
            <p>Pellentesque eleifend malesuada efficitur. Curabitur volutpat dui mi, ac imperdiet dolor tincidunt nec.
                Ut erat lectus, dictum sit amet lectus a, aliquet rutrum mauris. Etiam nec lectus hendrerit, consectetur
                risus viverra, iaculis orci. Phasellus eu nibh ut mi luctus auctor. Donec sit amet dolor in diam feugiat
                venenatis. </p>

            <ul class="icons">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <p class="copyright">&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a
                    href="https://unsplash.com/">Unsplash</a>. Videos: <a href="http://coverr.co/">Coverr</a>.</p>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="{% static 'courses/jquery.min.js' %}"></script>
    <script src="{% static 'courses/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'courses/jquery.poptrox.min.js' %}"></script>
    <script src="{% static 'courses/skel.min.js' %}"></script>
    <script src="{% static 'courses/util.js' %}"></script>
    <script src="{% static 'courses/main.js' %}"></script>

</body>

</html>